/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * VerdanTech Webapp Server
 * Server of the VerdanTech web application.
 * OpenAPI spec version: 0.0.1
 */
import type {
	PostUsersConfirmEmailBody,
	PostUsersConfirmPasswordResetBody,
	PostUsersCreateBody,
	PostUsersLoginBody,
	PostUsersRequestEmailConfirmationBody,
	PostUsersRequestPasswordResetBody,
	PostUsersUpdateBody
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

export const postUsersLogin = (postUsersLoginBody: PostUsersLoginBody) => {
	return axiosClient<string>({
		url: `/users/login`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersLoginBody
	});
};
export const postUsersRefresh = () => {
	return axiosClient<string>({ url: `/users/refresh`, method: 'POST' });
};
export const postUsersCreate = (postUsersCreateBody: PostUsersCreateBody) => {
	return axiosClient<string>({
		url: `/users/create`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersCreateBody
	});
};
export const postUsersUpdate = (postUsersUpdateBody: PostUsersUpdateBody) => {
	return axiosClient<string>({
		url: `/users/update`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersUpdateBody
	});
};
export const postUsersRequestEmailConfirmation = (
	postUsersRequestEmailConfirmationBody: PostUsersRequestEmailConfirmationBody
) => {
	return axiosClient<string>({
		url: `/users/requestEmailConfirmation`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersRequestEmailConfirmationBody
	});
};
export const postUsersConfirmEmail = (
	postUsersConfirmEmailBody: PostUsersConfirmEmailBody
) => {
	return axiosClient<string>({
		url: `/users/confirmEmail`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersConfirmEmailBody
	});
};
export const postUsersRequestPasswordReset = (
	postUsersRequestPasswordResetBody: PostUsersRequestPasswordResetBody
) => {
	return axiosClient<string>({
		url: `/users/requestPasswordReset`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersRequestPasswordResetBody
	});
};
export const postUsersConfirmPasswordReset = (
	postUsersConfirmPasswordResetBody: PostUsersConfirmPasswordResetBody
) => {
	return axiosClient<string>({
		url: `/users/confirmPasswordReset`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: postUsersConfirmPasswordResetBody
	});
};
