version: '3.9'

services:
  verdantech-backend:
    init: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
      
  verdantech-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 5173
    volumes:
      - /app/node_modules
      - .:/app

  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: xkrytusefhrerifuthrh
      POSTGRES_USER: verdantech_db
      POSTGRES_DB: dev_db
      