version: '3.9'

services:
  verdantech-backend:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:postgres
      
  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: xkrytusefhrerifuthrh
      POSTGRES_USER: verdantech_db
      POSTGRES_DB: dev_db

  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"