version: '3.8'

services:

  reverse-proxy:
    image: nginx:1.23.3
    container_name: reverse_proxy
    depends_on:
      - api
      - client
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  client:
    image: client
    container_name: client
    build:
      context: ./client
    depends_on:
      - api
    expose:
      - 8000
    restart: on-failure

  api:
    image: api
    container_name: api
    build:
      context: ./api
    expose:
      - 5000
