components:
  schemas: {}
info:
  title: Litestar API
  version: 1.0.0
openapi: 3.1.0
paths:
  /vdtapi/users/write/create:
    get:
      deprecated: false
      description: Register a new user and send an email verification
      operationId: VdtapiUsersWriteCreateUserCreate
      responses:
        '200':
          description: Request fulfilled, document follows
          headers: {}
      summary: User registration
      tags:
      - users
servers:
- url: /
