/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech Webapp Server
 * Server of the VerdanTech web application.
 * OpenAPI spec version: 0.0.1
 */
import type {
	UserConfirmEmailBody,
	UserConfirmPasswordResetBody,
	UserCreateBody,
	UserLoginBody,
	UserRequestEmailConfirmationBody,
	UserRequestPasswordResetBody,
	UserUpdateBody
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

/**
 * Grants an access and refresh token on a correct username and password.
 */
export const userLogin = (userLoginBody: UserLoginBody) => {
	return axiosClient<string>({
		url: `/users/login`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userLoginBody
	});
};
/**
 * Grants an access and refresh token on a valid refresh token.
 */
export const userRefresh = () => {
	return axiosClient<string>({ url: `/users/refresh`, method: 'POST' });
};
/**
 * Creates a new user.
 */
export const userCreate = (userCreateBody: UserCreateBody) => {
	return axiosClient<string>({
		url: `/users/create`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userCreateBody
	});
};
/**
 * Updates a user's username, email, or password
 */
export const userUpdate = (userUpdateBody: UserUpdateBody) => {
	return axiosClient<string>({
		url: `/users/update`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userUpdateBody
	});
};
/**
 * Requests an email confirmation be sent to the email address.
 */
export const userRequestEmailConfirmation = (
	userRequestEmailConfirmationBody: UserRequestEmailConfirmationBody
) => {
	return axiosClient<string>({
		url: `/users/requestEmailConfirmation`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userRequestEmailConfirmationBody
	});
};
/**
 * Confirms an email confirmation and verifies the email.
 */
export const userConfirmEmail = (userConfirmEmailBody: UserConfirmEmailBody) => {
	return axiosClient<string>({
		url: `/users/confirmEmail`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userConfirmEmailBody
	});
};
/**
 * Requests a password reset confirmation be sent to the email.
 */
export const userRequestPasswordReset = (
	userRequestPasswordResetBody: UserRequestPasswordResetBody
) => {
	return axiosClient<string>({
		url: `/users/requestPasswordReset`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userRequestPasswordResetBody
	});
};
/**
 * Confirms a password reset and changes the user's password
 */
export const userConfirmPasswordReset = (
	userConfirmPasswordResetBody: UserConfirmPasswordResetBody
) => {
	return axiosClient<string>({
		url: `/users/confirmPasswordReset`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: userConfirmPasswordResetBody
	});
};
export type UserLoginResult = NonNullable<Awaited<ReturnType<typeof userLogin>>>;
export type UserRefreshResult = NonNullable<Awaited<ReturnType<typeof userRefresh>>>;
export type UserCreateResult = NonNullable<Awaited<ReturnType<typeof userCreate>>>;
export type UserUpdateResult = NonNullable<Awaited<ReturnType<typeof userUpdate>>>;
export type UserRequestEmailConfirmationResult = NonNullable<
	Awaited<ReturnType<typeof userRequestEmailConfirmation>>
>;
export type UserConfirmEmailResult = NonNullable<
	Awaited<ReturnType<typeof userConfirmEmail>>
>;
export type UserRequestPasswordResetResult = NonNullable<
	Awaited<ReturnType<typeof userRequestPasswordReset>>
>;
export type UserConfirmPasswordResetResult = NonNullable<
	Awaited<ReturnType<typeof userConfirmPasswordReset>>
>;
