version: '3.9'

services:
  webapp:
    init: true
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - /app/node_modules
      - .:/app
      - .:/workspace:cached
    command: sleep infinity
    # network_mode: service:postgres
    expose:
      - 5173

  postgres:
    image: postgres:latest
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: xkrytusefhrerifuthrh
      POSTGRES_USER: verdantech_db
      POSTGRES_DB: dev_db
      