version: '3.9'

services:
  webapp:
    init: true
    image: node:23
    expose:
      - 5173
    volumes:
      - /app/node_modules
      - .:/app
      - .:/workspace:cached
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sleep infinity
  
  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    expose:
      - 1025
      - 8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1