version: '3.9'

services:
  webapp:
    init: true
    expose:
      - 5173
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sleep infinity

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    expose:
      - 1025
      - 8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH: 'severSmtpUser:serverSmtpPassword'
