/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Verdagraph Webapp Server
 * Server of the Verdagraph web application.
 * OpenAPI spec version: 0.0.1
 */

export type UserConfirmPasswordResetOpBody = {
	/**
	 * Must be between 6 and 255 characters long and contain at least one lowercase letter, one uppercase letter, one digit, and one special character.
	 * @minLength 6
	 * @maxLength 255
	 * @pattern ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W).*$
	 */
	password1: string;
	/**
	 * Must be between 6 and 255 characters long and contain at least one lowercase letter, one uppercase letter, one digit, and one special character.
	 * @minLength 6
	 * @maxLength 255
	 * @pattern ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W).*$
	 */
	password2: string;
	token: string;
	/** @pattern ^[a-zA-Z0-9_-]{21}$ */
	userId: string;
};
