/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech Webapp Server
 * Server of the VerdanTech web application.
 * OpenAPI spec version: 0.0.1
 */

export type UserLoginOpBody = {
	/** Must be a valid email address. */
	email: string;
	password: string;
};
