/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Verdagraph Webapp Server
 * Server of the Verdagraph web application.
 * OpenAPI spec version: 0.0.1
 */

export type UserConfirmEmailOpBody = {
	token: string;
};
