/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech Webapp Server
 * Server of the VerdanTech web application.
 * OpenAPI spec version: 0.0.1
 */

export type UserLoginBody = {
	/** Must be a valid email address. */
	email: string;
	/**
	 * Must be between 6 and 255 characters long and contain at least one lowercase letter, one uppercase letter, one digit, and one special character.
	 * @minLength 6
	 * @maxLength 255
	 * @pattern ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W).*$
	 */
	password: string;
};
