site_name: VerdanTech-API 

theme:
  name: material
  palette:
    scheme: slate

plugins:
- search
- mkdocstrings:
    default_handler: python


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format