site_name: VerdanTech-API 

nav:
  - Home: 'index.md'
  - Setup: 'setup.md'
  - Changelog: 'changelog.md'
  - Roadmap: 'roadmap.md'
  - Architecture: 'architecture.md'
  - OpenAPI: 'openapi.md'
  - 'Codebase':
    - 'Overview': 'codebase/overview.md'
    - 'Settings': 'codebase/settings.md' 
    - 'Domain':
      - 'Overview': 'codebase/domain/overview.md'
      - 'Models':
        - 'User': 'codebase/domain/models/user.md'
      - 'Interfaces':
        - 'Serializer': 'codebase/domain/interfaces/serializer.md'
        - 'Repository': 'codebase/domain/interfaces/repository.md'
        - 'Email': 'codebase/domain/interfaces/email.md'
        - 'Password Encryption': 'codebase/domain/interfaces/password_crypt.md'
      - 'Utilities':
        - 'Sanitizers': 'codebase/domain/utilities/sanitizers.md'
    - 'Application':
      - 'User': 'codebase/application/user.md'
    - 'API':
      - 'Litestar': codebase/api/litestar.md
    - 'Infrastructure':
      - 'Serializer': 'codebase/infrastructure/serializer.md'
      - 'Repository': 'codebase/infrastructure/repository.md'
      - 'Email': 'codebase/infrastructure/email.md'
      - 'Password Encryption': 'codebase/infrastructure/password_crypt.md'

  - Contributing: 'contributing.md'
  - Release Notes: 'release_notes.md'
  - Community: 'community.md'

theme:
  name: material
  palette:
    scheme: slate

plugins:
- search
- mkdocstrings:
    default_handler: python


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format